### ISSUE TITLE
internal functions - make them more easily identifiable

### ISSUE THREAD

**Issue by tomwilsonsco** [ScotGovAnalysis/cssampling#10]
There are a lot of internal functions within the RAP, which is fine of course. 

However, it can be tricky when working through the code to know whether functions such as `sampling` are internal or external. If internal functions were more easily identified it might help people who are needing to understand the code in future.

Ideas so far:
1. Store the internal functions in a list so when using in the scripts it is obvious where coming from e.g. called from a list `cs_fns` like `cs_fns$sampling(...)`

2. Name all the functions and script files in the functions directory with a prefix e.g. css_ so then would know are internal.

Not an essential change, but it might help interpretability and usability in the future.

**Comment by emmaschw** [comment]
I agree, it was quite difficult to distinguish between internal and external functions. 

I personally prefer the second idea and have added a `css_ ` prefix to all internal functions (eb2c592 and 2149e78).
