### ISSUE TITLE
Change process for local authority code - description

### ISSUE THREAD

**Issue by tomwilsonsco** [ScotGovAnalysis/cssampling#7]
Might be beneficial to break this large `ifelse`  decode so not hard coded into `01_paf.R`
Reading it in as a lookup table or dataframe and using a join to update might be faster.
Also keeps the `01_paf.R` script shorter
https://github.com/ScotGovAnalysis/cssampling/blob/2c98c18a1e20848ff96b2a995f6ff460d8181c01/scripts/01_paf.R#L263-L328

**Comment by emmaschw** [comment]
Good idea! I've implemented this with 8518d5c and 86d20e7.
